### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by badonyt** [ConnerConnerConner/PyTime-Website#1]
Hey so instead of always updating to have the latest .zip. 
You should instead is always naming your zips the same thing. So then you can just put https://github.com/ConnerConnerConner/releases/latest/download/[ur zip name that is always equal].zip.

So no need to keep puting the latest zip in the sites src

**Comment by ConnerConnerConner** [comment]
I will do this right now, thank you!

**Comment by ConnerConnerConner** [comment]
done, thanks!
